version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    pull_request:
      labels:
        - automerge
      auto_merge: true

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    pull_request:
      labels:
        - automerge
      auto_merge: true
